# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AudioUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 452)
        MainWindow.setMinimumSize(QtCore.QSize(690, 452))
        MainWindow.setMaximumSize(QtCore.QSize(690, 452))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(50, 60, 200, 30))
        self.textBrowser.setMinimumSize(QtCore.QSize(200, 30))
        self.textBrowser.setMaximumSize(QtCore.QSize(200, 30))
        self.textBrowser.setObjectName("textBrowser")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 100, 102, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.load_wav_file_btn = QtWidgets.QToolButton(self.widget)
        self.load_wav_file_btn.setMinimumSize(QtCore.QSize(100, 20))
        self.load_wav_file_btn.setMaximumSize(QtCore.QSize(100, 20))
        self.load_wav_file_btn.setObjectName("load_wav_file_btn")
        self.verticalLayout.addWidget(self.load_wav_file_btn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.connect_to_server_btn = QtWidgets.QToolButton(self.widget)
        self.connect_to_server_btn.setMinimumSize(QtCore.QSize(100, 20))
        self.connect_to_server_btn.setMaximumSize(QtCore.QSize(100, 20))
        self.connect_to_server_btn.setObjectName("connect_to_server_btn")
        self.verticalLayout.addWidget(self.connect_to_server_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.load_wav_file_btn.setText(_translate("MainWindow", "Load"))
        self.connect_to_server_btn.setText(_translate("MainWindow", "Connect"))
