# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AudioUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(690, 452)
        MainWindow.setMinimumSize(QtCore.QSize(690, 452))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 20, 154, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.text_brows_wav_file_info = QtWidgets.QTextBrowser(self.widget)
        self.text_brows_wav_file_info.setMinimumSize(QtCore.QSize(150, 50))
        self.text_brows_wav_file_info.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.text_brows_wav_file_info.setFont(font)
        self.text_brows_wav_file_info.setObjectName("text_brows_wav_file_info")
        self.verticalLayout_2.addWidget(self.text_brows_wav_file_info)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_load_wav_file = QtWidgets.QToolButton(self.widget)
        self.btn_load_wav_file.setMinimumSize(QtCore.QSize(150, 20))
        self.btn_load_wav_file.setMaximumSize(QtCore.QSize(100, 20))
        self.btn_load_wav_file.setObjectName("btn_load_wav_file")
        self.verticalLayout.addWidget(self.btn_load_wav_file)
        self.btn_connect_to_server = QtWidgets.QToolButton(self.widget)
        self.btn_connect_to_server.setMinimumSize(QtCore.QSize(150, 20))
        self.btn_connect_to_server.setMaximumSize(QtCore.QSize(100, 20))
        self.btn_connect_to_server.setObjectName("btn_connect_to_server")
        self.verticalLayout.addWidget(self.btn_connect_to_server)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Audio"))
        self.btn_load_wav_file.setText(_translate("MainWindow", "Load"))
        self.btn_connect_to_server.setText(_translate("MainWindow", "Connect"))
